// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TestResMjs from "src/Test.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

console.log("Hello, world");

function Demo(props) {
  return JsxRuntime.jsx("div", {
              children: TestResMjs()
            });
}

var make = Demo;

export {
  make ,
}
/*  Not a pure module */
